import argparse
import logging
from inferable.data import get_datasets
from inferable.models import get_models
from inferable.evaluation.evaluator import evaluate
from inferable.prediction.prediction import predict
from inferable.kg.kg_generation import write_n_triple_file
from typing import List
import os
import sys
import random


def dir_path(string):
    if os.path.isdir(string):
        return string
    else:
        raise NotADirectoryError(string)

def file_path(string):
    if os.path.isfile(string):
        return string
    else:
        raise FileNotFoundError(string)
    
def setup_parser() -> argparse.ArgumentParser:
    parent_parser = argparse.ArgumentParser(add_help=False)                                 
    parent_parser.add_argument(
        "--gpu", "-g", help="The GPUs to use (will be passed to CUDA_VISIBLE_DEVICES) e.g. `0,1` or '0'"
    )
    parent_parser.add_argument(
        "--verbose", "-v", help="increase output verbosity", action="store_true"
    )

    parser = argparse.ArgumentParser(prog='BZK', formatter_class=argparse.RawTextHelpFormatter)
    subparsers = parser.add_subparsers(help='subcommand help')

    #eval subparser
    eval_parser = subparsers.add_parser('evaluate', aliases=['eval'], help='This runs a evaluation of a model on a dataset', parents = [parent_parser])
    eval_parser.add_argument(
        "--models", "-m", nargs='+', help="Names of models e.g. `Dummy`, `Donut`, `PaliGemma`, `InternvlModel`", required=True
    )
    eval_parser.add_argument(
        "--datasets", "-d", nargs='+', help="Name of datasets e.g. `bzk_norm`, `bzk_raw`, `bzk_small_norm`, `bzk_small_raw`", required=True
    )
    eval_parser.add_argument(
        "--out", "-o", type=dir_path, help="Folder of the output files", default="output"
    )
    eval_parser.set_defaults(func=run_evaluation)


    #predict subparser
    predict_parser = subparsers.add_parser('predict', help='This runs a prediction of a model on a folder of input files', parents = [parent_parser])
    predict_parser.add_argument(
        "--model", "-m", help="Name of one model e.g. `Dummy`, `Donut`, `PaliGemma`, `InternvlModel`", required=True
    )
    predict_parser.add_argument(
        "--input", "-i", type=dir_path, help="Folder of the input files", required=True
    )
    predict_parser.add_argument(
        "--prediction", "-p", help="Path to the generated prediction file (should end with .jsonl or .jsonl.gz - will be compressed if it ends with .gz)", required=True
    )
    predict_parser.set_defaults(func=run_prediction)

    # kg generation subparser
    kg_parser = subparsers.add_parser('kg', help='This generates a knowledge graph from a prediction file', parents = [parent_parser])
    kg_parser.add_argument(
        "--prediction", "-p", type=file_path, help="File path to the prediction file generated by the previous step", required=True
    )
    kg_parser.add_argument(
        "--kgfile", "-k", help="Path to the generated kg file (should end with .nt or .nt.gz - will be compressed if it ends with .gz)", required=True
    )
    kg_parser.set_defaults(func=run_kg_generation)
    return parser

def run_evaluation(args: argparse.Namespace) -> None:
    models = get_models(args.models)
    datasets = get_datasets(args.datasets)
    evaluate(models, datasets, args.out)

def run_prediction(args: argparse.Namespace) -> None:
    models = get_models(args.model)
    predict(models[0], args.input, args.prediction)

def run_kg_generation(args: argparse.Namespace) -> None:
    write_n_triple_file(args.prediction, args.kgfile)

def parse_eval_args(parser: argparse.ArgumentParser, cmd_arguments: List[str]) -> argparse.Namespace:
    args = parser.parse_args(args=cmd_arguments)

    log_format = "%(asctime)s %(levelname)s %(message)s"

    if args.verbose:
        logging.basicConfig(level=logging.DEBUG, format=log_format)
    else:
        logging.basicConfig(level=logging.INFO, format=log_format)
    
    if args.gpu:
        os.environ["CUDA_VISIBLE_DEVICES"] = args.gpu

    # setting random seeds
    seed = 42
    random.seed(seed)
    import numpy as np 
    np.random.seed(seed) # importing here because of cuda visible devices set before
    import torch
    torch.manual_seed(seed)

    return args

def write_test_data() -> None:
    import random
    import json
    dataset = get_datasets(['bzk_small_raw'])[0].get_test_data()    
    with open('test_data.jsonl', 'w', encoding='utf-8') as file:
        for entry in dataset:
            del entry['image']
            entry['path'] = 'test_data/'
            entry['modelname'] = 'paligemma'
            entry['filename'] = str(random.randint(0, 10000)) + '.jpg'
            json.dump(entry, file)
            file.write('\n')

def cli_evaluate() -> None:
    cmd_arguments = sys.argv[1:]
    #cmd_arguments = [
        #"eval", "-d", "bzk_small_raw", "-m", "class=Dummy"
        #"eval", "-d", "bzk_small_raw", "-m", "class=PaliGemma", "-g", "1"
        #"eval", "-d", "bzk_small_raw", "-m", "class=Dummy"
        #"eval", "-d", "bzk_small_raw", "-m", "class=Donut,model_name=naver-clova-ix/donut-base-finetuned-cord-v2"
        #"eval", "-d", "bzk_small_raw", "-m", "class=Donut", "-g", "1"
        #"eval", "-d", "bzk_small_raw", "-m", "class=PaliGemmaZeroShot,model_name=/home/sven/BZK-InformationExtraction/output/paligemma_model/2024-10-11_19-44-24", "-g", "1"
        #"eval", "-d", "bzk_small_raw", "-m", "class=DonutModelZeroShot,model_name=output/donut_model/2024-07-27_08-40-01,task_prompt=<s_wieder>" 
        #"eval", "-d", "bzk_small_raw", "-m", "class=InternvlModel"
        #"eval", "-d", "bzk_small_raw", "-m", "class=InternvlWriteTraining,root_folder=/home/sven/bzk_train_internvl/InternVL/internvl_chat"
        #"eval", "-d", "bzk_small_raw", "-m", "class=InternvlWriteTraining,root_folder=train_folder"

       #"eval", "-d", "bzk_small_raw", "-m", "class=Dummy", "-g", "1"

        # write knowledge graph
        #"kg", "-p", "test_data.jsonl", "-k", "test_data.nt"
    #]

    
    parser = setup_parser()
    args = parse_eval_args(parser, cmd_arguments)
    args.func(args)

if __name__ == "__main__":
    cli_evaluate()